"""Auto-generated by setup/onetime_setup.py — launches the Browden SSE server.

Task Scheduler can't inject env vars, so set them here before importing the
server module (which reads MCP_* at import time), then run it.
"""
import os
import runpy
import sys

os.environ.setdefault("MCP_TRANSPORT", "sse")
os.environ.setdefault("MCP_HOST", "127.0.0.1")
os.environ.setdefault("MCP_PORT", "{port}")
sys.argv = ["browden", "--allowlist", r"{allowlist}"]
runpy.run_module("browden.mcp.server", run_name="__main__")
